#Ejercicio 1
print('E1: Despliegue')
print('Matrícula: A01362713')
print('Nombre:    Horacio Lamas Arellano')
#Ejercicio 2
print('E2: Flechas')
print('    *      *')
print('    **    **')
print('*******  *******')
print('    **    **')
print('    *      *')
#Ejercicio 3
print('E3: Figuras')
print('********* ***     *     *')
print('*        *    * *   ***    * *')
print('*        *   *   * *****   * *')
print('*        *   *   *   *    *   *')
print('*        *   *   *   *    *   *')
print('*        *   *   *   *     *  *')
print('*        *   *   *   *     *  *')
print('*        *   *   *   *     *  *')
print('********      ***    *      **')
#Ejercicio 4
print('E4: Matrícula')
print('**** **** * **** **** **** **** * ****')
print('*  * *  * *    * *       *    * *    *')
print('*  * *  * *    * *       *    * *    *')
print('**** *  * * **** ****    * **** * ****')
print('*  * *  * *    * *  *    * *    *    *')
print('*  * *  * *    * *  *    * *    *    *')
print('*  * **** * **** ****    * **** * ****')
#Ejercicio 5
print('E5: Pino')
print('   *   ')
print('  ***  ')
print(' ***** ')
print('*******')
print('   *   ')
print('   *   ')
#Ejercicio 6
print('E6: Cara')
print('***  *')
print('*  * *')
print('***  *')
print('*  * *')
print('***  *')
#Ejercicio 7
print('E7: Carrito')
print('   *****   ')
print('   *****   ')
print('***********')
print('***********')
print(' **     ** ')
print(' **     ** ')
